AppAlgebra/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('', include('Usuarios.urls')),
    path('', include('Ejercicios.urls')),
    path('', include('Examen.urls')),
    path('', include('Tareas.urls')),
    path('', include('Grupos.urls')),
    path("_reload_/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Examen/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # path('', views.login),
    # path('registro', views.registro)
]

Grupos/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # path('', views.login),
    path('materias', views.listar_materias),
    path('dashboard/<int:nrc>/', views.dashboard, name='dashboard'),
    path('materias_prueba', views.listar_materias_profesor, name='materias_prueba'),
    path('crear-grupo', views.crearGrupo, name='crear-grupo'),
    path('mis_materias', views.mis_materias, name='mis_materias'),
    path('buscar_materias', views.listar_materias, name="buscar_materias"),
    path('detalles_materia/<int:nrc>/', views.detalles_materia, name="detalles_materia"),
    path('inscripcion_materia/<int:nrc>/', views.inscripcion_materia, name="inscripcion_materia")
    #path('dashboard', views.dashboard)
]

Grupos/models.py
from django.db import models

# Create your models here.
# class Grupo(models.Model):
#     nombre = models.CharField(max_length=100)
#     nrc = models.IntegerField()
#     profesor = models.ForeignKey('Usuarios.Profesor', on_delete=models.CASCADE)
#     imagen = models

#     def __str__(self):
#         return str(self.nrc) 



def default_imagen():
    return 'default_imagen.jpg'

class Grupo(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.CharField(max_length=400, default="Sin descripción")
    nrc = models.IntegerField()
    profesor = models.ForeignKey('Usuarios.Profesor', on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='media/', default=default_imagen, null=True, blank=True)

    def __str__(self):
        return self.nombre + str(self.nrc)

Grupos/views.py
from django.shortcuts import render, redirect
from .models import Grupo
from .form import RegistroGrupo, BuscarMateriaForm, GrupoInscripcionForm
from django.contrib import messages

#Vistas generales
def listar_materias(request):
    materias = Grupo.objects.all()
    form = BuscarMateriaForm()

    if request.method == "POST":
        form = BuscarMateriaForm(request.POST)
        if form.is_valid():
            nrc_nombre = form.cleaned_data['nrc']

            if nrc_nombre:
                # Realizar la búsqueda por NRC o nombre (puedes personalizar la lógica de búsqueda)
                materias = materias.filter(nrc=nrc_nombre) | materias.filter(nombre__icontains=nrc_nombre)

    return render(request, 'materias.html', {'materias': materias, 'form': form})

## Vistas Profesores
#Crea un grupo Profesor
def crearGrupo(request):
    if request.method == 'POST':
        form = RegistroGrupo(request.POST, request.FILES)
        if form.is_valid():
            grupo = form.save(commit=False)
            # Realiza cualquier manipulación adicional con los datos del formulario aquí
            if not grupo.imagen:  # Verificar si no se seleccionó una imagen
                grupo.imagen = 'default_imagen.jpg'  # Asignar la imagen por defecto definida en el modelo
            grupo.profesor = request.user.profesor
            grupo.save()  # Guardar el objeto Grupo en la base de datos
            return redirect('index')
    else:
        form = RegistroGrupo()
    messages.success(request, 'Registro exitoso. Ahora puedes iniciar sesión.')
    return render(request, 'crear_grupo.html', {'form': form})

#Listar materias por profesores
def listar_materias_profesor(request):
    if request.user.is_authenticated and request.user.es_profesor:
        user = request.user
        profesor_id = user.id
        materias = Grupo.objects.filter(profesor__id=profesor_id)

         # Agregar conteo de estudiantes en cada grupo
        for materia in materias:
            materia.numero_estudiantes = materia.alumnos_inscritos.count()
            
    return render(request,'listar_materias_profesores.html', {'materias': materias})

## Vistas Alumnos
#Listar materias por alumnos
def listar_materias_alumno(request):
    if request.user.is_authenticated:
        user = request.user
        #materias = Grupo.objects.filter(profesor__id=profesor_id)
    return render(request,'listar_materias_alumno.html', {})

def dashboard(request, nrc):
    return render(request, 'dashboard.html', {'nrc': nrc})

#Registro a materia
def detalles_materia(request, nrc):
    materia = Grupo.objects.get(nrc=nrc)
    return render(request, 'detalles_materia.html', {'materia': materia})

def inscripcion_materia(request, nrc):
    try:
        materia = Grupo.objects.get(nrc=nrc)
        request.user.alumno.grupos_inscritos.add(materia)
        return redirect('index') 
    except Grupo.DoesNotExist:
        return render(request,"index")

def mis_materias (request):
    if request.user.is_authenticated:
        user = request.user
        materias = user.alumno.grupos_inscritos.all()   
    return render(request, 'mis_materias.html',{'user': user, 'materias': materias})

Grupos/templates/crear_grupo.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear grupo</title>
</head>

<body>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
    </ul>
    {% endif %}
    <div class="form-container">
        <h2>Nuevo grupo</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="nombre">Nombre:</label>
                {{ form.nombre }}
            </div>
            <div class="form-group">
                <label for="nrc" id="nrc-label">NRC:</label>
                {{ form.nrc }}
            </div>
            <div class="form-group">
                <label for="id_imagen">Imagen:</label>
                {{ form.imagen }}
              </div>
            <div class="form-submit">
                <input type="submit" value="Registrarse">
            </div>
            {% if form.errors %}
            <div class="alert alert-danger">
                {% for field in form %}
                {% for error in field.errors %}
                    <p>{{ error }}</p>
                {% endfor %}
                {% endfor %}
            </div>
            {% endif %}
        </form>
    </div>
</body>

</html>

Grupos/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard Invitado</title>
</head>
<body>
    <h2>Detalles de la materia</h2>
    <p>NRC: {{ nrc }}</p>
</body>
</html>

Grupos/templates/detalles_materia.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AppAlgebra | Materias</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/nav-bar.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>

<body>
    <div id="materia-seleccionada" class="materia-seleccionada vertical-center align-items-center justify-content-center" data-materia-id="{{ materia.nrc}}">
        <div class="materia-seleccionada-conteiner d-flex align-items-center justify-content-center">
            <div class="materias-card-img vertical-center align-items-center justify-content-center">
                <img src="{{ materia.imagen.url }}" alt="img_porfile">
                <h3 class="title">{{ materia.nombre }}</h3>
            </div>

            <div class="materias-card-content vertical-center pl-5">
                <label>Profesor(a): </label>
                <p class="profesor">{{ materia.profesor }}</p>
                <label>NRC:</label>
                <p class="nrc">NRC: {{ materia.nrc }}</p>
                <label>Descripcion</label>
                <p class="descripcion">{{ materia.descripcion }}</h3>
            </div>

        </div>
        <div class="materia-seleccionada-botones">
            <a href="{% url 'inscripcion_materia' materia.nrc %}" class="boton-primary registrarse">Registrarse en esta materia</a>
            <a href="/materias" class="boton-primary">Cancelar</a>
        </div>
        

    </div>
</body>

Grupos/templates/inscripcion.html
<form method="POST">
    {% csrf_token %}
    {{ form.grupos_seleccionados.label_tag }}
    {% for grupo in form.grupos_seleccionados %}
        {{ grupo.tag }}
        {{ grupo.choice_label }}
        <br>
    {% endfor %}
    <button type="submit">Inscribirse</button>
</form>

Grupos/templates/listar_materias_alumno.html
{% load static %}
<div class="card-container">
    <div class="card-alumno">
        <div class="card-image">
            <a href="#">
                <img src="{% static '/images/default_imagen.jpg' %}" alt="img_porfile">
            </a>
        </div>
        <div class="card-content">
            <h3 class="card-title">Algebra</h3>
        </div>
    </div>
    <div class="card-alumno">
        <div class="card-image">
            <a href="#">
                <img src="{% static '/images/default_imagen.jpg' %}" alt="img_porfile">
            </a>
        </div>
        <div class="card-content">
            <h3 class="card-title">Algebra</h3>
        </div>
    </div>
    <div class="card-alumno">
        <div class="card-image">
            <a href="#">
                <img src="{% static '/images/default_imagen.jpg' %}" alt="img_porfile">
            </a>
        </div>
        <div class="card-content">
            <h3 class="card-title">Algebra</h3>
        </div>
    </div>
    <div class="card-alumno">
        <div class="card-image">
            <a href="#">
                <img src="{% static '/images/default_imagen.jpg' %}" alt="img_porfile">
            </a>
        </div>
        <div class="card-content">
            <h3 class="card-title">Algebra</h3>
        </div>
    </div>
</div>

Grupos/templates/listar_materias_profesores.html
<div class="card-container">
    {% for materia in materias %}
    <div class="card-profesor">
        <div class="card-content">
            <h3 class="card-title">{{ materia.nombre }}</h3>
            <p class="card-nrc">NRC: {{ materia.nrc }}</p>
            <p class="score">{{ materia.numero_estudiantes }}</p>
            <p>estudiantes</p>
        </div>
        <div class="card-image">
            <a href="{% url 'dashboard' materia.nrc %}" >
                <img src="{{ materia.imagen.url }}" alt="img_porfile">
            </a>
        </div>
    </div>
    {% endfor %}
</div>

Grupos/templates/materias.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AppAlgebra | Materias</title>
    <style>
        .card-container {
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
        }

        .card {
            width: 300px;
            margin: 20px;
            padding: 10px;
            background-color: #f5f5f5;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        .card-image img {
            width: 100%;
            height: auto;
            border-radius: 8px;
        }

        .card-content {
            margin-top: 10px;
        }

        .card-title {
            font-size: 18px;
            font-weight: bold;
        }

        .card-profesor {
            font-size: 14px;
            color: #666;
        }

        .card-nrc {
            font-size: 14px;
            color: #888;
            margin-top: 5px;
        }
    </style>
</head>

<body>
    <form method="POST">
        <label class="block  text-gray-700 text-xs font-bold mb-2" for="grid-password">Ingresa el NRC de tu materia para
            ingresar a su contenido:</label>
        <input type="nrc" id="nrc" name="nrc"
            class="border-0 px-3 py-3 placeholder-gray-400 text-gray-700 bg-white rounded text-sm shadow focus:outline-none focus:ring w-full"
            style="transition: all 0.15s ease 0s;" required />
        <button
            class="bg-gray-900 text-white active:bg-gray-700 text-sm font-bold  px-6 py-3 rounded shadow hover:shadow-lg outline-none focus:outline-none mr-1 mb-1 w-full"
            type="submit" style="transition: all 0.15s ease 0s;">Buscar</button>
    </form>
    <h1>Listado de Materias</h1>
    <div class="card-container">
        {% for materia in materias %}
        <div class="card">
            <a href="{% url 'dashboard' materia.nrc %}" class="card-image">
                <img src="{{ materia.imagen.url }}" alt="img_porfile">
            </a>
            <div class="card-content">
                <h3 class="card-title">{{ materia.nombre }}</h3>
                <p class="card-profesor">{{ materia.profesor }}</p>
                <p class="card-nrc">NRC: {{ materia.nrc }}</p>
            </div>
        </div>
        {% endfor %}
    </div>
</body>

</html>

Grupos/templates/mis_materias.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AppAlgebra | Mis materias</title>

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/nav-bar.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</head>
<body>
    <div id="sideNavigation" class="sidenav ">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        <div class="sidebar_inner" id="sidebar_inner">
            <div class="text-center">
                <img class="imagen_perfil" src="{{ user.imagen_de_perfil.url }}" alt="img_porfile">
                <h5 class="p-2">{{ user.nombre }}</h5>
            </div>

            <ul class="link-nav">
                <li><a href="/index"> <span class="fas fa-home"></span>Home</a></li>
                <li><a href="/perfil"> <span class="fas fa-user"></span> Mi perfil</a></li>
                <li><a href="#"><span class="fas fa-book"></span> Mis materias</a></li>
                <li><a href="{% url 'cerrar_sesion' %}"><span class="fas fa-sign-out-alt"></span> Cerrar sesión</a></li>
            </ul>
        </div>
    </div>
    <div id="overlay"></div>
    <nav class="topnav sidebar_hide">
        <a href="#" onclick="openNav()">
            <svg width="30" height="30" id="icoOpen">
                <path d="M0,5 30,5" stroke="#000" stroke-width="5" />
                <path d="M0,14 30,14" stroke="#000" stroke-width="5" />
                <path d="M0,23 30,23" stroke="#000" stroke-width="5" />
            </svg>
        </a>
    </nav>
    <section class="content-100">
        <header>
            <div class="container text-center">
                <img class="logo_vertical" src="{% static '/images/logo_vertical.png' %}" alt="img_porfile">
            </div>
            <nav class="navbar navbar-expand-lg navbar-light">
                <div class="pr-4 pl-5 pt-4 pb-4 collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item mr-5">
                            <a class="nav-item-link" href="/index">Home </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-item-link act" href="#">Mis materias</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <div class="materias" id="materias">
            {% for materia in materias %}
            <a href="{% url '_materia' materia.nrc %}" class="materias-link" data-materia-id="{{ materia.nrc }}">
                <div class="materias-card">
                    <div class="materias-card-img">

                        <img src="{{ materia.imagen.url }}" alt="img_porfile">
                    </div>

                    <div class="materias-card-content">
                        <h3 class="title">{{ materia.nombre }}</h3>
                        <p class="profesor">{{ materia.profesor }}</p>
                        <p class="nrc">NRC: {{ materia.nrc }}</p>
                    </div>
                </div>
            </a>
            {% endfor %}
        </div>

    </section>
    <script src="{% static 'js/main.js'%}"></script>
</body>

</html>