AppAlgebra/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('', include('Usuarios.urls')),
    path('', include('Ejercicios.urls')),
    path('', include('Examen.urls')),
    path('', include('Tareas.urls')),
    path('', include('Grupos.urls')),
    path("_reload_/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Examen/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # path('', views.login),
    # path('registro', views.registro)
]

Usuarios/urls.py
from django.urls import path
from . import views
from django.contrib import admin

urlpatterns = [
    path('', views.login_view, name='login_view'),
    path('registro', views.registro),
    path('index', views.index, name='index'),
    path('cerrar-sesion', views.cerrar_sesion, name='cerrar_sesion'),
    path('recuperar_pass', views.recuperar_pass, name='recuperar_pass'),
    path('buscar_materia', views.buscarMateria, name='buscarMateria'),
    path('editar_perfil', views.editar_perfil, name='editar_perfil'),
    path('perfil', views.perfil, name='perfil')
   # path('crear_grupo', views.)
]

Usuarios/models.py
from asyncio import AbstractServer
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from Grupos.models import Grupo
from django.contrib.auth.models import AbstractUser


# Create your models here.


class UsuarioManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("El correo electrónico es obligatorio")
        
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('es_profesor', True)
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(email, password, **extra_fields)

class Usuario(AbstractBaseUser, PermissionsMixin):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=100)
    imagen_de_perfil = models.ImageField(upload_to='media/', default='img_porfile/default.png' , null=True, blank=True)
    es_profesor = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['nombre', 'apellido']

    objects = UsuarioManager()

    def __str__(self):
        return self.nombre +' '+ self.apellido

class Alumno(Usuario):
    matricula = models.PositiveSmallIntegerField()
    grupos_inscritos = models.ManyToManyField(Grupo, related_name='alumnos_inscritos', blank=True)

class Profesor(Usuario):
    matriculaP = models.IntegerField()

Usuarios/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Alumno
from Grupos.models import Grupo
from django import forms
from .models import Alumno, Profesor

class Registro(forms.ModelForm):
    nombre = forms.CharField(max_length=100)
    apellido = forms.CharField(max_length=100)
    email = forms.EmailField()
    matricula = forms.IntegerField()
    nrc = forms.ModelChoiceField(queryset=Grupo.objects.all(), required=False)
    password = forms.CharField(label='Contraseña', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirmar contraseña', widget=forms.PasswordInput)
    es_alumno = forms.BooleanField(required=False, initial=True, widget=forms.CheckboxInput(attrs={'id': 'es_alumno','class':'form-check-label'}))

    class Meta:
        model = Alumno
        fields = ('nombre', 'apellido', 'email', 'password', 'password2',  'matricula', 'nrc') 

class AlumnoEditForm(forms.ModelForm):
    class Meta:
        model = Alumno
        fields = ['nombre', 'apellido', 'email', 'imagen_de_perfil']

    imagen_de_perfil = forms.ImageField(
        required=True,  # Hacer que el campo de imagen sea requerido
        widget=forms.ClearableFileInput(attrs={'accept': 'image/*'})
    )

Usuarios/views.py
from django.shortcuts import render
from .models import Alumno, Profesor, Grupo
from django.shortcuts import render, redirect
from .forms import Registro, AlumnoEditForm
from django.contrib.auth import logout
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here.
@login_required
def index(request):
    if request.user.is_authenticated:
        user = request.user
        nombre = f"{user.nombre} {user.apellido}" 
        imagen_de_perfil = user.imagen_de_perfil
        es_profesor = request.user.es_profesor
        if es_profesor:
            profesor_id = user.id
            materias = Grupo.objects.filter(profesor__id=profesor_id)
            return render(request, 'index.html', {'es_profesor': es_profesor , 'materias': materias, 'imagen_de_perfil':imagen_de_perfil, 'nombre': nombre})
        else:
            materias_inscritas = materias_inscritas = request.user.alumno.grupos_inscritos.all()
            return render(request, 'index.html', {'es_profesor': es_profesor , 'materias': materias_inscritas, 'imagen_de_perfil':imagen_de_perfil, 'nombre': nombre})
    else:
        # El usuario necesita iniciar sesion
        return render(request, 'login.html')
   
def login_view(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(request, email=email, password=password)
        if user is not None:
            # El usuario es válido, iniciar sesión
            login(request, user)
            return redirect('index')  # Redirecciona a la página de inicio después del inicio de sesión exitoso
        else:
            # El usuario no es válido, mostrar mensaje de error
            error_message = "Credenciales inválidas. Por favor, intenta nuevamente."
            return render(request, 'login.html', {'error_message': error_message})
    else:
        return render(request,"login.html")

def registro(request):
    if request.method == 'POST':
        form = Registro(request.POST)
        if form.is_valid():
            nombre = form.cleaned_data['nombre']
            apellido = form.cleaned_data['apellido']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            matricula = form.cleaned_data['matricula']
            es_alumno = form.cleaned_data['es_alumno']
            nrc = form.cleaned_data['nrc']
            img_perfil = 'img_porfile/default.png'
            if es_alumno:
                Alumno.objects.create_user(email=email, 
                                           password=password,
                                           nombre=nombre,
                                           apellido=apellido,
                                           matricula=matricula,
                                           grupo=nrc,
                                           es_profesor=False,
                                           imagen_de_perfil=img_perfil
                                           )
            else:
                Profesor.objects.create_user(email=email, 
                                            password=password,
                                            nombre=nombre,
                                            apellido=apellido,
                                            matriculaP=matricula,
                                            es_profesor=True,
                                            imagen_de_perfil=img_perfil
                                            )
                
            messages.success(request, 'Registro exitoso. Ahora puedes iniciar sesión.')
            return redirect('login_view')  # Redirecciona a la página de inicio o a donde desees después del registro exitoso
    else:
        form = Registro()
    return render(request, 'registro.html', {'form': form})

def recuperar_pass(request):
    return render(request, 'pass_reset.html')

def buscarMateria(request):
    return render(request,'input_NRC.html')

def cerrar_sesion(request):
    logout(request)
    return redirect('login_view')

def perfil(request):
    return render(request, 'perfil.html')

def editar_perfil(request):
    alumno = request.user  # Obtener el usuario actual

    if request.method == 'POST':
        form = AlumnoEditForm(request.POST, request.FILES, instance=alumno)

        if form.is_valid():
            # Verificar si el formulario se ha modificado
            if form.has_changed():
                form.save()
                messages.success(request, 'Cambios guardados exitosamente.')
            else:
                messages.info(request, 'No se registraron cambios.')

            return redirect('perfil')  # Cambia 'perfil' por la URL de la página de perfil del alumno
    else:
        form = AlumnoEditForm(instance=alumno)

    return render(request, 'editar_perfil.html', {'form': form})

Usuarios/templates/editar_perfil.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AppAlgebra | Editar Perfil</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/nav-bar.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="{% static 'js/main.js'%}"></script>
</head>

<body>
    <div id="sideNavigation" class="sidenav ">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        <div class="sidebar_inner">
            <div class="text-center">
                <img class="imagen_perfil" src="{{ user.imagen_de_perfil.url }}" alt="img_porfile">
                <h5 class="p-2">{{ nombre }}</h5>
            </div>

            <ul class="link-nav">
                <li><a href="/index"> <span class="fas fa-home"></span>Home</a></li>
                <li><a href="/perfil"> <span class="fas fa-user"></span> Mi perfil</a></li>
                <li><a href="#"><span class="fas fa-book"></span> Mis materias</a></li>
                <li><a href="#"><span class="fas fa-search"></span> Buscar materia</a></li>
                <li><a href="{% url 'cerrar_sesion' %}"><span class="fas fa-sign-out-alt"></span> Cerrar sesión</a></li>
            </ul>
        </div>
    </div>
    <div id="overlay"></div>
    <nav class="topnav sidebar_hide">
        <a href="#" onclick="openNav()">
            <svg width="30" height="30" id="icoOpen">
                <path d="M0,5 30,5" stroke="#000" stroke-width="5" />
                <path d="M0,14 30,14" stroke="#000" stroke-width="5" />
                <path d="M0,23 30,23" stroke="#000" stroke-width="5" />
            </svg>
        </a>
    </nav>
    <section class="content-100">
        <header>
            <div class="container text-center">
                <img class="logo_vertical" src="{% static '/images/logo_vertical.png' %}" alt="img_porfile">
            </div>
            <nav class="navbar navbar-expand-lg navbar-light">
                <div class="p-5 collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-item-link" href="/index">Home</a>
                        </li>
                    </ul>
                </div>
            </nav>

        </header>
        <div class="container editar-perfil">
            <div class="row">
                <div class="col-md-auto d-flex align-items-center">
                    <img class="imagen_perfil" src="{{ user.imagen_de_perfil.url }}" alt="img_porfile">
                </div>
                <div class="col aling-center">
                    {% if messages %}
                    <div class="messages">
                        {% for message in messages %}
                        <div class="message{% if message.tags %} {{ message.tags }}{% endif %}">
                            {{ message }}
                        </div>
                        {% endfor %}
                    </div>
                    {% endif %}

                    <form method="post" class="form-editar-perfil" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.nombre.label_tag }} {{ form.nombre }}
                        {{ form.apellido.label_tag }} {{ form.apellido }}
                        {{ form.email.label_tag }} {{ form.email }}

                        <div>
                            <label for="id_imagen_de_perfil">Imagen de Perfil:</label>
                            {{ form.imagen_de_perfil }}
                        </div>

                        <button type="submit">Guardar</button>
                        <a href="{% url 'index' %}">Cancelar</a>
                    </form>

                </div>
            </div>
        </div>
    </section>

</body>

</html>

Usuarios/templates/index.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Home - App Algebra</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <!-- <link rel='stylesheet' type='text/css' media='screen' href='main.css'> -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
{% if user.es_profesor %}
<!-- Contenido para profesor -->

<body>
    <header class="header">
        <div class="container text-center">
            <img class="logo_vertical" src="{% static '/images/logo_vertical.png' %}" alt="img_porfile">
        </div>
        <nav class="navbar navbar-expand-lg navbar-light">
            <!--  -->
            <!-- <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button> -->

            <div class="p-5 collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav mr-auto">

                    <li class="nav-item mr-5">
                        <a class="nav-item-link act" href="#">Home </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item-link" href="/materias_prueba">Mis grupos</a>
                    </li>
                </ul>
                <h5 class="pr-5">Bienvenido, profesor</h5>
            </div>
        </nav>
    </header>

    <div class="sidebar">
        <div class="sidebar_inner">
            <div class="text-center">
                <img class="imagen_perfil" src="{{ user.imagen_de_perfil.url }}" alt="img_porfile">
                <h5 class="text-black p-2">{{ nombre }}</h5>
            </div>

            <ul class="link-nav">
                <li><a href="#"> <span class="fas fa-user"></span> Mi perfil</a></li>
                <li><a href="#"><span class="fas fa-book"></span> Mis materias</a></li>
                <li><a href="#"><span class="fas fa-edit"></span> Configuración</a></li>
                <li><a href="{% url 'cerrar_sesion' %}"><span class="fas fa-sign-out-alt"></span> Cerrar sesión</a></li>
            </ul>
        </div>
    </div>

    <section class="content">
        {% include 'listar_materias_profesores.html' %}
        <!-- {% include 'notificaciones.html' %} -->
    </section>

</body>

{% else %}

<body>
    <header class="header">
        <div class="container text-center">
            <img class="logo_vertical" src="{% static '/images/logo_vertical.png' %}" alt="img_porfile">
        </div>
        <nav class="navbar navbar-expand-lg navbar-light">
            <div class="pr-4 pl-5 pt-4 collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item mr-5">
                        <a class="nav-item-link act" href="#">Home </a>
                    </li>
                    <li class="nav-item mr-5">
                        <a class="nav-item-link" href="#">Tareas</a>
                    </li>
                    <li class="nav-item mr-5">
                        <a class="nav-item-link" href="#">Exámenes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item-link" href="#">Material de Soporte</a>
                    </li>
                </ul>
                <h5 class="pr-5">Bienvenido</h5>
            </div>
        </nav>

    </header>

    <section class="alumno sidebar">
        <div class="sidebar_inner">
            <div class="text-center">
                <img class="imagen_perfil" src="{{ user.imagen_de_perfil.url }}" alt="img_porfile">
                <h5 class="p-2">{{ nombre }}</h5>
            </div>

            <ul class="link-nav">
                <li><a href="/perfil"> <span class="fas fa-user"></span> Mi perfil</a></li>
                <li><a href="/editar_perfil"><span class="fas fa-edit"></span>Editar perfil</a></li>
                <li><a href="/mis_materias"><span class="fas fa-book"></span> Mis materias</a></li>
                <li><a href="/materias"><span class="fas fa-search"></span> Buscar materia</a></li>
                <li><a href="{% url 'cerrar_sesion' %}"><span class="fas fa-sign-out-alt"></span> Cerrar sesión</a></li>
            </ul>
        </div>
    </section>

    <section class="content">
        <div class="materias ml-8">
            {% for materia in materias %}
            <div class="card-container">
                <div class="card-alumno">
                    <div class="card-image">
                        <a href="#">
                            <img src="{{materia.imagen.url}}" alt="img_porfile">
                        </a>
                    </div>
                    <div class="card-content">
                        <h3 class="card-title">{{ materia.nombre}}</h3>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

        <div class="notificaciones ml-9 mt-5 mb-5">
            <label>Notificaciones</label>
            <div class="panel-notificaciones">
                <div class="item-notificacion">Nueva tarea publicada de tu curso de Algebra ll</div>
                <div class="item-notificacion">Nueva tarea publicada de tu curso de Algebra ll</div>
                <div class="item-notificacion">Nueva tarea publicada de tu curso de Algebra ll</div>
                <div class="item-notificacion">Nueva tarea publicada de tu curso de Algebra ll</div>
            </div>
        </div>

    </section>

</body>
{% endif %}

</html>

Usuarios/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>AppAlgebra | Login</title>
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>

<body>
    <nav ></nav>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 vertical-center">
                <div class="slider">
                    <img src="{% static '/images/logo.png' %}" alt="AppAlgebra Logo">
                </div>
            </div>
            <div class="col-md-6 vertical-center">
                <h1>Inicia sesión para continuar</h1>
                {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                            {% endfor %}
                    </ul>
                    {% endif %}
                    <form method="POST">
                        {% csrf_token %}
                        {% if error_message %}
                        <div class="text-red-500 mb-4">{{ error_message }}</div>
                        {% endif %}
                        <div class="w-full mb-3">
                            <p class="block mb-2 pt-2"
                                for="grid-password">Correo electrónico</p>
                            <input type="email" id="email" name="email"
                                class="border-0 mt-2 placeholder-gray-400  text-sm focus:outline-none focus:ring w-full"
                                style="transition: all 0.15s ease 0s;" required />
                        </div>
                        <div class=" w-full mb-3">
                            <p class="block mb-2 pt-2"
                                for="grid-password">Contraseña</p>
                            <input type="password" id="password" name="password"
                                class="border-0 mt-2 placeholder-gray-400  text-sm focus:outline-none focus:ring w-full"
                                style="transition: all 0.15s ease 0s;" required />
                        </div>
                        <div class="text-sm flex items-start justify-between">
                            <p for="password"
                                class="block text-sm font-sans font-medium leading-6 text-gray-900">¿Olvidaste
                                tu contraseña?</p>
                            <a href="/recuperar_pass"
                                class="font-semibold text-indigo-600 font-sans hover:text-indigo-500">Recuperar
                                contraseña</a>
                        </div>
                        <div class="text-center mt-6">
                            <button
                                class="boton-primary"
                                type="submit" style="transition: all 0.15s ease 0s;">
                                Iniciar sesión
                            </button>
                        </div>
                    </form>
                    <hr class="mt-6 border-b-1 border-gray-400" />
                    <div class="flex flex-wrap">
                        <div class="w-full">
                            <small>¿No tienes cuenta?</small>
                            <a href="/registro" class="text-indigo-600">
                                <small>Registrate</small></a> <br>
                            <small>Ingresa como <a href="/materias"
                                    class="font-semibold leading-6 text-indigo-600 font-sans hover:text-indigo-500">invitado</a>
                                para realizar los ejercicios de práctica sólo necesitas el NRC de tú
                                materia</small>

                        </div>
                    </div>
            </div>

        </div>
    </div>
    

</body>

</html>

Usuarios/templates/pass_reset.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Reset</title>
</head>
<body>
    <h1>Recupera tu contraseña</h1>
    <p>Contacta al administrador para resetear tu contraseña</p>
    
</body>
</html>

Usuarios/templates/perfil.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Perfil</title>

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/nav-bar.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="{% static 'js/main.js'%}"></script>
</head>
<body>
    <h1>Aqui va contenido del perfil</h1>
</body>
</html>

Usuarios/templates/registro.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>AppAlgebra | Registro</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 vertical-center">
                <div class="slider">
                    <img src="{% static '/images/logo.png' %}" alt="AppAlgebra Logo">
                </div>
            </div>
            <div class="col-md-6 vertical-center">
                <div class="form-container">
                    <h4 class="pb-3">Registro de usuario</h4>
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <p for="nombre">Nombre:</p>
                            {{ form.nombre }}
                        </div>
                        <div class="form-group">
                            <p for="apellido">Apellido:</p>
                            {{ form.apellido }}
                        </div>
                        <div class="form-group">
                            <p for="email">Email:</p>
                            {{ form.email }}
                        </div>
                        <div class="form-group">
                            <p for="password">Contraseña:</p>
                            {{ form.password }}
                        </div>
                        <div class="form-group">
                            <p for="password2">Confirmar contraseña:</p>
                            {{ form.password2 }}
                        </div>
                        <div class="form-group">
                            <p for="matricula">Matrícula:</p>
                            {{ form.matricula }}
                        </div>
                        <div class="form-group">
                            <p for="nrc" id="nrc">NRC:</p>
                            {{ form.nrc }}
                        </div>
                        <div class="form-group form-check form-check-inline">
                            <p class="form-check-label" for="es_alumno">Soy alumno:  </p>
                            {{ form.es_alumno }}
                        </div>
                        <div class="form-submit">
                            <input class="boton-primary" type="submit" value="Registrarse">
                        </div>
                        {% if form.errors %}
                        <div class="alert alert-danger">
                            {% for field in form %}
                            {% for error in field.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                            {% endfor %}
                        </div>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script>
        const alumnoCheckbox = document.getElementById('es_alumno');
        const nrcLabel = document.getElementById('nrc');
        const nrcInput = document.getElementById('id_nrc');
    
        alumnoCheckbox.addEventListener('change', function() {
            if (alumnoCheckbox.checked) {
                nrcLabel.style.display = 'block';
                nrcInput.style.display = 'block';
            } else {
                nrcLabel.style.display = 'none';
                nrcInput.style.display = 'none';
            }
        });
    </script>
</body>
</html>